### ISSUE TITLE
Nant not recognising the generate-msbuild XML Node

### ISSUE THREAD

**Issue by RDalziel** [skolima/generate-msbuild#1]
I've tried following the instructions and placed the generated DLL from the project in with my accompanying nant DLLs but that doesn't seem to be enough to allow for the new XML node to be allowed.

What else am i missing from the instructions?

This tool looks great by the way ! :)

**Comment by skolima** [comment]
Please try running NAnt with `-debug -logfile:debug_log.txt` and attach the result here, I'll see if I can help.

**Comment by RDalziel** [comment]
Hi Skolima!

I managed to get passed the problem by adding an additional line to the line you mentioned. See below

![image](https://f.cloud.github.com/assets/3485935/1198013/f5a9abb0-24eb-11e3-9bac-cf6c72339df3.png)

**Comment by skolima** [comment]
You can also put the task assembly in <Project Base Directory>/extensions/common/neutral/  and NAnt will load it automatically, without the need for <loadtasks/>. I'll update the README to mention that. Source: http://nant.sourceforge.net/release/latest/help/fundamentals/tasks.html#automatic-project
